stages:
  - test
  - build
  - deploy_dev
  - deploy_prod

variables:
  PROJECT_NAME: "ecommerce"
  IMAGE_LATEST: "$CI_REGISTRY_IMAGE:latest"
  IMAGE_SHA: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

test:
  stage: test
  image: python:3.12-slim
  services:
    - name: postgres:16
      alias: db
  variables:
    POSTGRES_DB: ecommerce
    POSTGRES_USER: ecommerce
    POSTGRES_PASSWORD: ecommerce
    POSTGRES_HOST: db
    POSTGRES_PORT: "5432"
    DJANGO_SETTINGS_MODULE: ecommerce.settings
  script:
    - pip install -r backend/requirements.txt
    - cd backend
    - python manage.py migrate
    - pytest || if [ $? -eq 5 ]; then echo "Aucun test trouvé, on continue."; else exit 1; fi
    - flake8 .
    - black --check .
  rules:
    - if: $CI_COMMIT_BRANCH

build:
  stage: build
  image: docker:27.3
  services:
    - docker:27.3-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -f infra/docker/backend.Dockerfile -t "$IMAGE_SHA" -t "$IMAGE_LATEST" --build-arg ENVIRONMENT=prod .
    - docker push "$IMAGE_SHA"
    - docker push "$IMAGE_LATEST"
  needs:
    - test
  rules:
    - if: $CI_COMMIT_BRANCH

deploy_dev:
  stage: deploy_dev
  tags:
    - local-runner
  script:
    - |
      echo "--- DÉMARRAGE DU DÉPLOIEMENT DEV ---"
      docker login -u "$env:CI_REGISTRY_USER" -p "$env:CI_REGISTRY_PASSWORD" "$env:CI_REGISTRY"
      echo "Login Docker réussi."
      @"
      DJANGO_DEBUG=1
      DJANGO_SECRET_KEY=$env:DJANGO_SECRET_KEY
      DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      POSTGRES_DB=ecommerce
      POSTGRES_USER=ecommerce
      POSTGRES_PASSWORD=ecommerce
      POSTGRES_HOST=db_dev
      POSTGRES_PORT=5432
      IMAGE_TAG=$env:IMAGE_LATEST
      "@ | Out-File -FilePath .env -Encoding ascii
      echo "Fichier .env créé. Démarrage de docker compose."
      docker compose --profile dev up -d --pull always
      echo "Docker Compose lancé. Exécution des migrations."
      docker compose --profile dev exec -T web python manage.py migrate --noinput
      echo "--- DÉPLOIEMENT DEV TERMINÉ ---"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  needs:
    - build
  when: on_success

deploy_prod:
  stage: deploy_prod
  tags:
    - local-runner
  script:
    - |
      echo "--- DÉMARRAGE DU DÉPLOIEMENT PROD (HTTP UNIQUEMENT) ---"
      docker login -u "$env:CI_REGISTRY_USER" -p "$env:CI_REGISTRY_PASSWORD" "$env:CI_REGISTRY"
      echo "Login Docker réussi."
      
      # Nettoyage du volume certs_data (pour être sûr)
      docker volume rm certs_data -f | Out-Null
      
      # Création du fichier .env
      @"
      DJANGO_DEBUG=0
      DJANGO_SECRET_KEY=$env:DJANGO_SECRET_KEY
      DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0 # Ajoutez votre domaine ici
      POSTGRES_DB=ecommerce
      POSTGRES_USER=ecommerce
      POSTGRES_PASSWORD=ecommerce
      POSTGRES_HOST=db_prod
      POSTGRES_PORT=5432
      IMAGE_TAG=$env:IMAGE_SHA
      "@ | Out-File -FilePath .env -Encoding ascii
      echo "Fichier .env créé. Démarrage de docker compose."
      
      # Démarrage, Migrations et Collecte Statique (Nginx ne lira que le HTTP)
      docker compose --profile prod up -d --pull always
      
      echo "Docker Compose lancé. Exécution des migrations."
      docker compose --profile prod exec -T web_prod python manage.py migrate --noinput
      echo "Collecte des fichiers statiques dans le volume partagé"
      docker compose --profile prod exec -T web_prod python manage.py collectstatic --noinput
      echo "--- DÉPLOIEMENT PROD TERMINÉ ---"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - build
  when: on_success