services:
  db:
    image: postgres:16
    profiles: ["dev", "prod"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - postgres_data:/var/lib/postgresql/data
  web:
    profiles: ["dev"]
    build:
    context: .
    dockerfile: infra/docker/backend.Dockerfile
    env_file:
    - .env
    environment:
      POSTGRES_HOST: db
    volumes:
    - ./backend:/app
    ports:
    - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
    - db
  web_prod:
    profiles: ["prod"]
    image: ${IMAGE_TAG}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
    - "8070:8000"
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  volumes:
    postgres_data: