# Fichier : infra/nginx/nginx_http.conf
server {
    listen 80;
    server_name localhost; # Remplacez par votre vrai domaine

    # Redirection permanente vers HTTPS
    return 301 https://$host$request_uri; 
}