# Fichier : infra/nginx/nginx_https.conf

upstream django {
    server web_prod:8000; 
}

server {
    listen 443 ssl;
    server_name localhost; # Remplacez par votre vrai domaine

    # 🛑 Placez VOS CERTIFICATS ICI
    ssl_certificate /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;

    # Paramètres de sécurité SSL recommandés
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # 1. Statiques
    location /static/ {
        alias /static/;
        expires 7d;
        add_header Cache-Control "public";
    }

    # 2. Application Django
    location / {
        proxy_pass http://django;
        proxy_read_timeout 120s;
        proxy_connect_timeout 120s;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https; # <-- Indiquer que la connexion est sécurisée
    }
}